package io.github.grpckotlin.generator

import com.google.protobuf.DescriptorProtos.FileDescriptorProto
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec

object ProtoFileCodeGenerator {
    fun generate(
        fileProto: FileDescriptorProto,
        config: GeneratorConfig,
        typeIndex: ProtoTypeIndex,
    ): List<CodeGeneratorResponse.File> {
        if (fileProto.serviceCount == 0) return emptyList()

        val kotlinPackage = DescriptorUtil.resolveKotlinPackage(fileProto, config)
        val comments = ProtoComments.of(fileProto)

        // When the proto enables `java_multiple_files` (or runs under edition
        // 2024+, where multi-file output is the default), mirror protoc-gen-
        // java's behaviour: emit one .kt file per service rather than bundling
        // them into a single <OuterClass>GrpcKt.kt.
        return if (DescriptorUtil.isJavaMultipleFiles(fileProto)) {
            fileProto.serviceList.mapIndexed { serviceIndex, service ->
                buildPerServiceFile(
                    ServiceContext(fileProto, service, serviceIndex, config, typeIndex, comments),
                )
            }
        } else {
            listOf(buildBundledFile(fileProto, kotlinPackage, config, typeIndex, comments))
        }
    }

    private fun buildPerServiceFile(ctx: ServiceContext): CodeGeneratorResponse.File {
        val fileSpec = newFileSpec(ctx.kotlinPackage, ctx.outerObjectName, ctx.file.name)
        fileSpec.addType(buildServiceObject(ctx))
        return outputFile(ctx.kotlinPackage, ctx.outerObjectName, fileSpec.build().toString())
    }

    private fun buildBundledFile(
        fileProto: FileDescriptorProto,
        kotlinPackage: String,
        config: GeneratorConfig,
        typeIndex: ProtoTypeIndex,
        comments: ProtoComments,
    ): CodeGeneratorResponse.File {
        val outerFileName = DescriptorUtil.outerKotlinClassNameForGrpcKt(fileProto)
        val fileSpec = newFileSpec(kotlinPackage, outerFileName, fileProto.name)
        fileProto.serviceList.forEachIndexed { serviceIndex, service ->
            val ctx = ServiceContext(fileProto, service, serviceIndex, config, typeIndex, comments)
            fileSpec.addType(buildServiceObject(ctx))
        }
        return outputFile(kotlinPackage, outerFileName, fileSpec.build().toString())
    }

    private fun buildServiceObject(ctx: ServiceContext): TypeSpec {
        val outerObject = TypeSpec.objectBuilder(ctx.outerObjectName)
        ctx.serviceComment()?.let { outerObject.addKdoc("%L", it) }
        ServiceNameGenerator.apply(outerObject, ctx)
        // Schema descriptors require Descriptors.FileDescriptor +
        // io.grpc.protobuf.Proto*DescriptorSupplier, neither of which exist
        // in the lite runtime (protobuf-javalite + grpc-protobuf-lite). In
        // lite mode the suppliers are dropped and `setSchemaDescriptor(...)`
        // is omitted from MethodDescriptor / ServiceDescriptor builders —
        // matching what upstream protoc-gen-grpc-java does for lite.
        if (!ctx.config.lite) DescriptorSuppliersGenerator.apply(outerObject, ctx)
        MethodDescriptorsGenerator.apply(outerObject, ctx)
        ServiceDescriptorGenerator.apply(outerObject, ctx)
        ClientStubGenerator.apply(outerObject, ctx)
        ServerBaseGenerator.apply(outerObject, ctx)
        return outerObject.build()
    }

    private fun newFileSpec(
        kotlinPackage: String,
        fileName: String,
        protoSourceName: String,
    ): FileSpec.Builder =
        FileSpec.builder(kotlinPackage, fileName)
            .indent("    ")
            .addFileComment(
                "Code generated by io.github.grpckotlin protoc-gen-grpc-kotlin. DO NOT EDIT.\n" +
                    "source: $protoSourceName\n"
            )

    private fun outputFile(
        kotlinPackage: String,
        fileName: String,
        content: String,
    ): CodeGeneratorResponse.File {
        val outputPath = if (kotlinPackage.isEmpty()) {
            "$fileName.kt"
        } else {
            "${kotlinPackage.replace('.', '/')}/$fileName.kt"
        }
        return CodeGeneratorResponse.File.newBuilder()
            .setName(outputPath)
            .setContent(content)
            .build()
    }
}
