package io.github.grpckotlin.generator

import com.google.protobuf.DescriptorProtos.FileDescriptorProto
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec

object ProtoFileCodeGenerator {
    fun generate(
        fileProto: FileDescriptorProto,
        config: GeneratorConfig,
        typeIndex: ProtoTypeIndex,
    ): List<CodeGeneratorResponse.File> {
        if (fileProto.serviceCount == 0) return emptyList()

        val kotlinPackage = DescriptorUtil.resolveKotlinPackage(fileProto, config)
        val outerFileName = DescriptorUtil.outerKotlinClassNameForGrpcKt(fileProto)
        val fileSpec = FileSpec.builder(kotlinPackage, outerFileName)
            .indent("    ")
            .addFileComment(
                "Code generated by io.github.grpckotlin protoc-gen-grpc-kotlin. DO NOT EDIT.\n" +
                    "source: ${fileProto.name}\n"
            )

        for (service in fileProto.serviceList) {
            val ctx = ServiceContext(fileProto, service, config, typeIndex)
            val outerObject = TypeSpec.objectBuilder(ctx.outerObjectName)
            ServiceNameGenerator.apply(outerObject, ctx)
            DescriptorSuppliersGenerator.apply(outerObject, ctx)
            MethodDescriptorsGenerator.apply(outerObject, ctx)
            ServiceDescriptorGenerator.apply(outerObject, ctx)
            ClientStubGenerator.apply(outerObject, ctx)
            ServerBaseGenerator.apply(outerObject, ctx)
            fileSpec.addType(outerObject.build())
        }

        val outputPath = if (kotlinPackage.isEmpty()) {
            "$outerFileName.kt"
        } else {
            "${kotlinPackage.replace('.', '/')}/$outerFileName.kt"
        }
        return listOf(
            CodeGeneratorResponse.File.newBuilder()
                .setName(outputPath)
                .setContent(fileSpec.build().toString())
                .build()
        )
    }
}
